# Generated by Django 3.2.9 on 2021-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
